# Generated by Django 2.2 on 2019-05-11 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_bigtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Art')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Bigtext')),
            ],
        ),
    ]
