# Generated by Django 2.2 on 2019-05-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.OS'),
        ),
    ]
